import fs from 'fs/promises';
import path from 'path';
import { IMemoryProvider, Memory } from '../../interfaces/IMemoryProvider.js';
import { v4 as uuidv4 } from 'uuid';

export class JsonMemoryProvider implements IMemoryProvider {
    private memoryPath: string;
    private memories: Memory[] = [];
    private initialized = false;

    constructor(workspaceRoot: string) {
        this.memoryPath = path.join(workspaceRoot, 'memory.json');
    }

    async init(): Promise<void> {
        if (this.initialized) return;

        try {
            const data = await fs.readFile(this.memoryPath, 'utf-8');
            const loaded = JSON.parse(data);
            // Hydrate dates
            this.memories = loaded.map((m: any) => ({
                ...m,
                createdAt: new Date(m.createdAt)
            }));
        } catch (error: any) {
            if (error.code === 'ENOENT') {
                this.memories = [];
                await this.save();
            } else {
                console.error(`Failed to load memory.json from ${this.memoryPath}:`, error);
                throw error;
            }
        }
        this.initialized = true;
    }

    async saveMemory(content: string, metadata: Record<string, any>, userId: string, agentId?: string): Promise<Memory> {
        await this.init();

        const memory: Memory = {
            uuid: uuidv4(),
            content,
            metadata,
            userId,
            agentId,
            createdAt: new Date(),
            // Embedding would be generated here or passed in. 
            // For JSON provider without dedicated vector DB, we might skip embeddings 
            // or store them if generated by an external service.
        };

        this.memories.push(memory);
        await this.save();
        return memory;
    }

    async searchMemories(query: string, userId: string, limit: number = 5, threshold: number = 0.7): Promise<Memory[]> {
        await this.init();

        // Simple search logic, without embeddings engine in pure JSON without extra libs
        // In a real implementation, we would compute cosine similarity if embeddings exist

        const results = this.memories.filter(m => m.userId === userId);

        // Basic keyword match fallback if no vector search
        const queryLower = query.toLowerCase();
        const matches = results.filter(m =>
            m.content.toLowerCase().includes(queryLower) ||
            JSON.stringify(m.metadata).toLowerCase().includes(queryLower)
        );

        return matches.slice(0, limit);
    }

    async listMemories(userId: string, limit: number = 20, offset: number = 0): Promise<Memory[]> {
        await this.init();
        const userMemories = this.memories
            .filter(m => m.userId === userId)
            .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());

        return userMemories.slice(offset, offset + limit);
    }

    async deleteMemory(uuid: string, userId: string): Promise<void> {
        await this.init();
        const initialLength = this.memories.length;
        this.memories = this.memories.filter(m => !(m.uuid === uuid && m.userId === userId));

        if (this.memories.length !== initialLength) {
            await this.save();
        }
    }

    private async save(): Promise<void> {
        await fs.writeFile(this.memoryPath, JSON.stringify(this.memories, null, 2), 'utf-8');
    }
}
