// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/callback" | "/conflict" | "/dashboard" | "/dashboard/agents" | "/dashboard/architecture" | "/dashboard/autopilot" | "/dashboard/billing" | "/dashboard/brain" | "/dashboard/browser" | "/dashboard/chronicle" | "/dashboard/cloud-dev" | "/dashboard/code" | "/dashboard/command" | "/dashboard/config" | "/dashboard/council" | "/dashboard/deer-flow" | "/dashboard/director" | "/dashboard/events" | "/dashboard/evolution" | "/dashboard/experts" | "/dashboard/healer" | "/dashboard/infrastructure" | "/dashboard/ingestion" | "/dashboard/inspector" | "/dashboard/jules" | "/dashboard/knowledge" | "/dashboard/library" | "/dashboard/manual" | "/dashboard/marketplace" | "/dashboard/mcp" | "/dashboard/mcp/agent" | "/dashboard/mcp/ai-tools" | "/dashboard/mcp/api-keys" | "/dashboard/mcp/audit" | "/dashboard/mcp/catalog" | "/dashboard/mcp/docs" | "/dashboard/mcp/endpoints" | "/dashboard/mcp/inspector" | "/dashboard/mcp/logs" | "/dashboard/mcp/metamcp" | "/dashboard/mcp/namespaces" | "/dashboard/mcp/observability" | "/dashboard/mcp/policies" | "/dashboard/mcp/registry" | "/dashboard/mcp/scripts" | "/dashboard/mcp/search" | "/dashboard/mcp/settings" | "/dashboard/mcp/system" | "/dashboard/mcp/tool-sets" | "/dashboard/mcp/tools" | "/dashboard/memory" | "/dashboard/memory/claude-mem" | "/dashboard/metamcp" | "/dashboard/metrics" | "/dashboard/plans" | "/dashboard/pulse" | "/dashboard/reader" | "/dashboard/research" | "/dashboard/security" | "/dashboard/session" | "/dashboard/settings" | "/dashboard/skills" | "/dashboard/squads" | "/dashboard/submodules" | "/dashboard/super-assistant" | "/dashboard/supervisor" | "/dashboard/swarm" | "/dashboard/symbols" | "/dashboard/webui" | "/dashboard/workflows" | "/dashboard/workshop" | "/dashboard/workshop/auto-dev" | "/docs" | "/docs/api" | "/docs/architecture" | "/docs/tools" | "/forgot-password" | "/guide" | "/login" | "/prompts" | "/reset-password" | "/signup"
type AppRouteHandlerRoutes = "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/reset-password" | "/api/auth/signup" | "/api/jules/[[...path]]" | "/api/monitoring/events" | "/api/monitoring/stats" | "/api/prompts" | "/api/trpc/[trpc]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/login"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/reset-password": {}
  "/api/auth/signup": {}
  "/api/jules/[[...path]]": { "path"?: string[]; }
  "/api/monitoring/events": {}
  "/api/monitoring/stats": {}
  "/api/prompts": {}
  "/api/trpc/[trpc]": { "trpc": string; }
  "/auth/callback": {}
  "/conflict": {}
  "/dashboard": {}
  "/dashboard/agents": {}
  "/dashboard/architecture": {}
  "/dashboard/autopilot": {}
  "/dashboard/billing": {}
  "/dashboard/brain": {}
  "/dashboard/browser": {}
  "/dashboard/chronicle": {}
  "/dashboard/cloud-dev": {}
  "/dashboard/code": {}
  "/dashboard/command": {}
  "/dashboard/config": {}
  "/dashboard/council": {}
  "/dashboard/deer-flow": {}
  "/dashboard/director": {}
  "/dashboard/events": {}
  "/dashboard/evolution": {}
  "/dashboard/experts": {}
  "/dashboard/healer": {}
  "/dashboard/infrastructure": {}
  "/dashboard/ingestion": {}
  "/dashboard/inspector": {}
  "/dashboard/jules": {}
  "/dashboard/knowledge": {}
  "/dashboard/library": {}
  "/dashboard/manual": {}
  "/dashboard/marketplace": {}
  "/dashboard/mcp": {}
  "/dashboard/mcp/agent": {}
  "/dashboard/mcp/ai-tools": {}
  "/dashboard/mcp/api-keys": {}
  "/dashboard/mcp/audit": {}
  "/dashboard/mcp/catalog": {}
  "/dashboard/mcp/docs": {}
  "/dashboard/mcp/endpoints": {}
  "/dashboard/mcp/inspector": {}
  "/dashboard/mcp/logs": {}
  "/dashboard/mcp/metamcp": {}
  "/dashboard/mcp/namespaces": {}
  "/dashboard/mcp/observability": {}
  "/dashboard/mcp/policies": {}
  "/dashboard/mcp/registry": {}
  "/dashboard/mcp/scripts": {}
  "/dashboard/mcp/search": {}
  "/dashboard/mcp/settings": {}
  "/dashboard/mcp/system": {}
  "/dashboard/mcp/tool-sets": {}
  "/dashboard/mcp/tools": {}
  "/dashboard/memory": {}
  "/dashboard/memory/claude-mem": {}
  "/dashboard/metamcp": {}
  "/dashboard/metrics": {}
  "/dashboard/plans": {}
  "/dashboard/pulse": {}
  "/dashboard/reader": {}
  "/dashboard/research": {}
  "/dashboard/security": {}
  "/dashboard/session": {}
  "/dashboard/settings": {}
  "/dashboard/skills": {}
  "/dashboard/squads": {}
  "/dashboard/submodules": {}
  "/dashboard/super-assistant": {}
  "/dashboard/supervisor": {}
  "/dashboard/swarm": {}
  "/dashboard/symbols": {}
  "/dashboard/webui": {}
  "/dashboard/workflows": {}
  "/dashboard/workshop": {}
  "/dashboard/workshop/auto-dev": {}
  "/docs": {}
  "/docs/api": {}
  "/docs/architecture": {}
  "/docs/tools": {}
  "/forgot-password": {}
  "/guide": {}
  "/login": {}
  "/prompts": {}
  "/reset-password": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/login": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
