// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/conflict/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conflict">> = Specific
  const handler = {} as typeof import("../../../src/app/conflict/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/architecture">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/autopilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/autopilot">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/autopilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/brain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/brain">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/brain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/browser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/browser">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/browser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/chronicle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/chronicle">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/chronicle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/cloud-dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cloud-dev">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/cloud-dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/code">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/command/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/command">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/command/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/config">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/council/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/council">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/council/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/deer-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/deer-flow">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/deer-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/director/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/director">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/director/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/evolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/evolution">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/evolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/experts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/experts">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/experts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/healer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/healer">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/healer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/infrastructure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/infrastructure">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/infrastructure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/ingestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ingestion">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/ingestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/inspector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inspector">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/inspector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/jules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/jules">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/jules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/knowledge">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/library">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/manual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/manual">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/manual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/marketplace">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/ai-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/ai-tools">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/ai-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/api-keys">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/catalog">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/endpoints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/endpoints">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/endpoints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/inspector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/inspector">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/inspector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/logs">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/metamcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/metamcp">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/metamcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/namespaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/namespaces">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/namespaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/observability">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/policies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/policies">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/policies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/registry">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/scripts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/scripts">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/scripts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/search">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/system">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/tool-sets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/tool-sets">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/tool-sets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/mcp/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/mcp/tools">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/mcp/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/memory/claude-mem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/memory/claude-mem">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/memory/claude-mem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/memory">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/metamcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metamcp">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/metamcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/plans">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/pulse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pulse">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/pulse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/reader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reader">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/reader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/research">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/security">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/session">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/skills">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/squads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/squads">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/squads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/submodules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/submodules">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/submodules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/super-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/super-assistant">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/super-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/supervisor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/supervisor">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/supervisor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/swarm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/swarm">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/swarm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/symbols/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/symbols">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/symbols/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/webui/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webui">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/webui/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/workflows">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/workshop/auto-dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/workshop/auto-dev">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/workshop/auto-dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/workshop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/workshop">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/workshop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/api">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/architecture">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/docs/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/tools">> = Specific
  const handler = {} as typeof import("../../../src/app/docs/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../../src/app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prompts">> = Specific
  const handler = {} as typeof import("../../../src/app/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/jules/[[...path]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jules/[[...path]]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/jules/[[...path]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/monitoring/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/monitoring/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/monitoring/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/monitoring/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prompts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trpc/[trpc]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trpc/[trpc]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trpc/[trpc]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
