// Code generated by scripts/generate_tools.py. DO NOT EDIT.
package tools

import (
	"encoding/json"
	"fmt"
)

func RegisterAutoGeneratedTools(r *Registry) {
	r.Tools = append(r.Tools, Tool{
		Name:        "insights",
		Description: "Generate a report analyzing your Claude Code sessions",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "insights"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "brief",
		Description: "Toggle brief-only mode",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "brief"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "review",
		Description: "Review a pull request",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "review"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "ultrareview",
		Description: "Tool ultrareview extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "ultrareview"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "security-review",
		Description: "Complete a security review of the pending changes on the current branch",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "security-review"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "version",
		Description: "Print the version this session is running (not what autoupdate downloaded)",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "version"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "init",
		Description: "Tool init extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "init"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "commit-push-pr",
		Description: "Commit, push, and open a PR",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "commit-push-pr"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "init-verifiers",
		Description: "Create verifier skill(s) for automated verification of code changes",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "init-verifiers"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "bridge-kick",
		Description: "Inject bridge failure states for manual recovery testing",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "bridge-kick"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "advisor",
		Description: "Configure the advisor model",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "advisor"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "commit",
		Description: "Create a git commit",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "commit"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "project_areas",
		Description: "Tool project_areas extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "project_areas"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "interaction_style",
		Description: "Tool interaction_style extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "interaction_style"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "what_works",
		Description: "Tool what_works extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "what_works"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "friction_analysis",
		Description: "Tool friction_analysis extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "friction_analysis"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "suggestions",
		Description: "Tool suggestions extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "suggestions"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "on_the_horizon",
		Description: "Tool on_the_horizon extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "on_the_horizon"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "cc_team_improvements",
		Description: "Tool cc_team_improvements extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "cc_team_improvements"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "model_behavior_improvements",
		Description: "Tool model_behavior_improvements extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "model_behavior_improvements"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "fun_ending",
		Description: "Tool fun_ending extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "fun_ending"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "at_a_glance",
		Description: "Tool at_a_glance extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "at_a_glance"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "tag",
		Description: "Toggle a searchable tag on the current session",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "tag"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "passes",
		Description: "Tool passes extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "passes"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "remote-env",
		Description: "Configure the default remote environment for teleport sessions",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "remote-env"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "thinkback-play",
		Description: "Play the thinkback animation",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "thinkback-play"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "usage",
		Description: "Show plan usage limits",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "usage"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "rate-limit-options",
		Description: "Show options when rate limit is reached",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "rate-limit-options"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "compact",
		Description: "Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "compact"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "terminal-setup",
		Description: "Tool terminal-setup extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "terminal-setup"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "export",
		Description: "Export the current conversation to a file or clipboard",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "export"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "agents",
		Description: "Manage agent configurations",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "agents"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "permissions",
		Description: "Manage allow & deny tool permission rules",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "permissions"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "branch",
		Description: "Create a branch of the current conversation at this point",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "branch"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "reload-plugins",
		Description: "Activate pending plugin changes in the current session",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "reload-plugins"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "config",
		Description: "Open config panel",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "config"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "mobile",
		Description: "Show QR code to download the Claude mobile app",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "mobile"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "install-slack-app",
		Description: "Install the Claude Slack app",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "install-slack-app"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "remote-control",
		Description: "Connect this terminal for remote-control sessions",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "remote-control"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "rewind",
		Description: "Tool rewind extracted automatically",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "rewind"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "upgrade",
		Description: "Upgrade to Max for higher rate limits and more Opus",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "upgrade"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "vim",
		Description: "Toggle between Vim and Normal editing modes",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "vim"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "hooks",
		Description: "View hook configurations for tool events",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "hooks"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "color",
		Description: "Set the prompt bar color for this session",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "color"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "tasks",
		Description: "List and manage background tasks",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "tasks"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "heapdump",
		Description: "Dump the JS heap to ~/Desktop",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "heapdump"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "btw",
		Description: "Ask a quick side question without interrupting the main conversation",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "btw"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "effort",
		Description: "Set effort level for model usage",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "effort"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "release-notes",
		Description: "View release notes",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "release-notes"), nil
		},
	})
	r.Tools = append(r.Tools, Tool{
		Name:        "diff",
		Description: "View uncommitted changes and per-turn diffs",
		Parameters:  json.RawMessage(`{"type":"object","properties":{},"additionalProperties":false}`),
		Execute: func(args map[string]interface{}) (string, error) {
			return fmt.Sprintf("Auto-generated tool '%s' executed", "diff"), nil
		},
	})

}
