export interface CliHarnessCatalogEntry {
    id: string;
    name: string;
    command: string;
    args: string[];
    homepage: string;
    docsUrl: string;
    installHint: string;
    category: 'cli' | 'cloud' | 'editor';
    sessionCapable: boolean;
    versionArgs: string[];
    detectionMode?: 'command' | 'manual';
}

export const CLI_HARNESS_CATALOG: CliHarnessCatalogEntry[] = [
    {
        id: 'borg',
        name: 'borg',
        command: 'borg',
        args: [],
        homepage: 'https://github.com/robertpelloni/borg',
        docsUrl: 'https://github.com/robertpelloni/borg',
        installHint: 'Use borg\'s tracked `submodules/borg` checkout or install borg and ensure `borg` is on PATH.',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['version'],
    },
    {
        id: 'aider',
        name: 'Aider',
        command: 'aider',
        args: [],
        homepage: 'https://aider.chat/',
        docsUrl: 'https://aider.chat/docs/',
        installHint: 'pip install aider-chat',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'antigravity',
        name: 'Antigravity',
        command: 'antigravity',
        args: [],
        homepage: 'https://antigravity.google/',
        docsUrl: 'https://antigravity.google/docs/home',
        installHint: 'Download the Antigravity desktop app from https://antigravity.google/download and launch it directly; borg does not currently detect it as a PATH CLI.',
        category: 'editor',
        sessionCapable: false,
        versionArgs: [],
        detectionMode: 'manual',
    },
    {
        id: 'claude',
        name: 'Claude Code',
        command: 'claude',
        args: [],
        homepage: 'https://www.anthropic.com/claude-code',
        docsUrl: 'https://docs.anthropic.com/en/docs/claude-code/overview',
        installHint: 'npm install -g @anthropic-ai/claude-code',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'codex',
        name: 'OpenAI Codex CLI',
        command: 'codex',
        args: [],
        homepage: 'https://platform.openai.com/docs/guides/codex',
        docsUrl: 'https://platform.openai.com/docs/guides/codex',
        installHint: 'Install the Codex CLI binary and make sure `codex` is on PATH.',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'gemini',
        name: 'Gemini CLI',
        command: 'gemini',
        args: [],
        homepage: 'https://ai.google.dev/gemini-api/docs/cli',
        docsUrl: 'https://ai.google.dev/gemini-api/docs',
        installHint: 'Install the Gemini CLI and ensure `gemini` is on PATH.',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'opencode',
        name: 'OpenCode',
        command: 'opencode',
        args: [],
        homepage: 'https://opencode.ai/',
        docsUrl: 'https://opencode.ai/docs',
        installHint: 'Install OpenCode and ensure `opencode` is on PATH.',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'cursor',
        name: 'Cursor CLI',
        command: 'cursor',
        args: [],
        homepage: 'https://cursor.com/',
        docsUrl: 'https://cursor.com/docs',
        installHint: 'Install Cursor and enable its shell command so `cursor` is available on PATH.',
        category: 'editor',
        sessionCapable: false,
        versionArgs: ['--version'],
    },
    {
        id: 'copilot',
        name: 'GitHub Copilot CLI',
        command: 'github-copilot-cli',
        args: [],
        homepage: 'https://github.com/features/copilot',
        docsUrl: 'https://docs.github.com/en/copilot',
        installHint: 'Install GitHub Copilot CLI and ensure `github-copilot-cli` or `gh copilot` is available.',
        category: 'cli',
        sessionCapable: false,
        versionArgs: ['--version'],
    },
    {
        id: 'goose',
        name: 'Goose CLI',
        command: 'goose',
        args: [],
        homepage: 'https://block.github.io/goose/',
        docsUrl: 'https://block.github.io/goose/docs/',
        installHint: 'Install Goose and ensure `goose` is on PATH.',
        category: 'cli',
        sessionCapable: false,
        versionArgs: ['--version'],
    },
    {
        id: 'qwen',
        name: 'Qwen Code CLI',
        command: 'qwen',
        args: [],
        homepage: 'https://chat.qwen.ai/',
        docsUrl: 'https://qwen.readthedocs.io/',
        installHint: 'Install the Qwen CLI and ensure `qwen` is on PATH.',
        category: 'cli',
        sessionCapable: false,
        versionArgs: ['--version'],
    },
    {
        id: 'superai-cli',
        name: 'SuperAI CLI',
        command: 'superai',
        args: [],
        homepage: 'https://superai.dev/',
        docsUrl: 'https://superai.dev/docs',
        installHint: 'npm install -g superai-cli',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'codebuff',
        name: 'Codebuff',
        command: 'codebuff',
        args: [],
        homepage: 'https://codebuff.com/',
        docsUrl: 'https://codebuff.com/docs',
        installHint: 'npm install -g codebuff',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'codemachine',
        name: 'CodeMachine',
        command: 'codemachine',
        args: [],
        homepage: 'https://codemachine.dev/',
        docsUrl: 'https://codemachine.dev/docs',
        installHint: 'npm install -g codemachine',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
    {
        id: 'factory-droid',
        name: 'Factory Droid',
        command: 'droid',
        args: [],
        homepage: 'https://factory.ai/',
        docsUrl: 'https://factory.ai/docs',
        installHint: 'Install Factory Droid and ensure `droid` is on PATH.',
        category: 'cli',
        sessionCapable: true,
        versionArgs: ['--version'],
    },
];

export const DEFAULT_SUPERVISED_COMMANDS = Object.fromEntries(
    CLI_HARNESS_CATALOG
        .filter((entry) => entry.sessionCapable && entry.detectionMode !== 'manual')
        .map((entry) => [entry.id, { command: entry.command, args: [...entry.args] }]),
) as Record<string, { command: string; args: string[] }>;
